#! /bin/sh

bspc rule -r "*"

pgrep -x sxhkd > /dev/null || sxhkd &

#bspc monitor -d I II III IV V VI VII VIII IX X

# Default 1 monitor with 6 workspaces
bspc monitor -d '1' '2' '3' '4' '5' '6'

bspc config border_width         0
bspc config window_gap           20
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer               false
bspc config pointer_follows_focus               false
bspc config pointer_motion_interval             5
bspc config pointer_modifier                    mod4
bspc config pointer_action1                     move
bspc config pointer_action2                     resize_side
bspc config pointer_action3                     resize_corner

#bspc config active_border_color \#E84F4F
#bspc config normal_border_color \#000000

#bspc config border_width 0

#AutoSart applications
#sxhkd &
picom --config $HOME/.config/picom/picom.conf &
nitrogen --restore &
dunst &
#polybar &
eww daemon
eww open bar
